OrderOverview/OrderOverview.WebApp/Controllers/AssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OrderOverview.WebApp.Controllers
{
    public class AssignmentController : Controller
    {
        // GET: Assignment
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult List()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }
    }
}

OrderOverview/OrderOverview.WebApp/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OrderOverview.WebApp.Controllers
{
    public class ClientController : Controller
    {
        // GET: Client
        public ActionResult List()
        {
            return View();
        }
    }
}

OrderOverview/OrderOverview.WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OrderOverview.WebApp.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            BusinessLayer.Test test = new BusinessLayer.Test();

            return View();
        }
    }
}

OrderOverview/OrderOverview.WebApp/Controllers/ProductCategoryController.cs
using OrderOverview.BusinessLayer;
using OrderOverview.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OrderOverview.WebApp.Controllers
{
    public class ProductCategoryController : Controller
    {
        // GET: ProductCategory

        ProductCategoryManager categoryManager = new ProductCategoryManager();

        public ActionResult Index(bool? ConfirmToastr)
        {
            if (ConfirmToastr.HasValue && ConfirmToastr.Value)
            {
                ViewBag.ConfirmSubmitMessage = "Alert!"; 
            }

        var categories = categoryManager.GetProductCategory();
            ViewBag.Categories = categories;
            return View();
        }

        [HttpPost]
        public ActionResult Create(ProductCategory category)
        {
            categoryManager.Insert(category);
            return RedirectToAction("Index");
        }

        public ActionResult Details()
        {
            return View();
        }
        public ActionResult Delete()
        {
            return View();
        }






    }
}

OrderOverview/OrderOverview.WebApp/Views/Assignment/Create.cshtml
    <!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">

            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Starter Page</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-2">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Auftrag</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="exampleInputFile">Auftragsnummer</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="text" placeholder="AUF-0001-2021-04-14" class="form-control">

                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputFile">Auftragsgeber</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="text" placeholder="Mitarbeitername" class="form-control">
                                        <span class="input-group-append">
                                            <button type="button" class="btn btn-primary btn-flat"><i class="fas fa-search"></i></button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Einrichtung</label>
                                <input type="text" class="form-control" id="exampleInput" placeholder="Einrichtungsname">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Mandant</label>
                                <input type="text" class="form-control" id="exampleInput" placeholder="Mandatname">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Ticketnummer</label>
                                <input type="text" class="form-control" id="exampleInput" placeholder="z. B. 10001">
                            </div>
                            <div class="form-group">
                                <label>Beschreibung</label>
                                <textarea class="form-control" rows="3" placeholder="Schreiben Sie hier etwas..."></textarea>
                            </div>
                            <div id="accordion">
                                <div class="card card-primary">
                                    <div class="card-header">
                                        <h4 class="card-title w-100">
                                            <a class="d-block w-100 collapsed" data-toggle="collapse" href="#collapseOne" aria-expanded="false">
                                                Gewünschte Produktskategorie
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseOne" class="collapse" data-parent="#accordion" style="">
                                        <div class="card-body p-0">
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th>Produktskategory</th>
                                                        <th>Maximalpreis</th>
                                                        <th>Mit Biterspiegel?</th>
                                                        <th style="width: 40px"></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td>
                                                            <select class="form-control">
                                                                <option>Notebook</option>
                                                                <option>Handy</option>
                                                                <option>Pc</option>
                                                                <option>Drucker</option>
                                                                <option>Zubehör</option>
                                                            </select>
                                                        </td>
                                                        <td>
                                                            <input type="text" class="form-control" placeholder="Euro...">
                                                        </td>
                                                        <td>
                                                            <div class="custom-control custom-checkbox">
                                                                <input class="custom-control-input custom-control-input-danger" type="checkbox" id="customCheckbox4">
                                                                <label for="customCheckbox4" class="custom-control-label"></label>
                                                            </div>
                                                        </td>
                                                        <td><button type="button" class="badge bg-success">hinzufügen</button></td>
                                                    </tr>

                                                </tbody>
                                            </table>
                                        </div>
                                        <hr />
                                        <div class="card-body">
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th>SN</th>
                                                        <th>Produktskategory</th>
                                                        <th>Maximalpreis</th>
                                                        <th>Mit Biterspiegel?</th>
                                                        <th style="width: 40px"></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td>1</td>
                                                        <td>Notebook</td>
                                                        <td>600</td>
                                                        <td>Ja</td>
                                                        <td><span class="badge bg-danger">Lösen</span></td>
                                                    </tr>
                                                    <tr>
                                                        <td>2</td>
                                                        <td>Handy</td>
                                                        <td>500</td>
                                                        <td>Ja</td>
                                                        <td><span class="badge bg-danger">Lösen</span></td>
                                                    </tr>
                                                    <tr>
                                                        <td>3</td>
                                                        <td>Zubehör</td>
                                                        <td>70</td>
                                                        <td>Nein</td>
                                                        <td><span class="badge bg-danger">Lösen</span></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>


                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Bestätigen</button>
                        </div>

                    </form>
                </div>

            </div>


        </div>

        <!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content -->

OrderOverview/OrderOverview.WebApp/Views/Assignment/Details.cshtml
<br />
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="card card-primary card-outline">

                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputFile">Auftraggeber</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="text" placeholder="Mitarbeitername" class="form-control">

                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Einrichtung</label>
                            <input type="text" class="form-control" id="exampleInput" placeholder="Einrichtungsname">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Mandant</label>
                            <input type="text" class="form-control" id="exampleInput" placeholder="Mandatname">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Ticketnummer</label>
                            <input type="text" class="form-control" id="exampleInput" placeholder="z. B. 10001">
                        </div>
                        <div class="form-group">
                            <label>Beschreibung</label>
                            <textarea class="form-control" rows="3" placeholder="Schreiben Sie hier etwas..."></textarea>
                        </div>
                    </div>
                    <!-- /.card-body -->

                </div>
                <div class="card">
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Produktskategory</th>
                                    <th>Maximalpreis</th>
                                    <th>Mit Biterspiegel?</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>Notebook</td>
                                    <td>600</td>
                                    <td>Ja</td>
                                    <td><button type="button" class="btn btn-block bg-gradient-success">Erstellt Bieterspiegel</button></td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>Handy</td>
                                    <td>500</td>
                                    <td>Ja</td>
                                    <td><button type="button" class="btn btn-block bg-gradient-success">Erstellt Bieterspiegel</button></td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>Zubehör</td>
                                    <td>70</td>
                                    <td>Nein</td>
                                    <td><button type="button" class="btn btn-block bg-gradient-warning">Bestellt Produkt</button></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="card-footer clearfix">
                        <a href="#" class="card-link">Zurück zur Liste</a>
                        <a href="#" class="card-link"> </a>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.row -->

    </div><!-- /.container-fluid -->
</section>

OrderOverview/OrderOverview.WebApp/Views/Assignment/List.cshtml
<!-- Auftragslist -->
<div class="card">
    <div class="card-header">
        <h1 class="m-0 text-dark">Auftrag</h1>
    </div>
    <br />
    <div class="col-md-12">
        <a class="btn btn-primary" href="/Assignment/Create" role="button"><i class="fas fa-file-signature fa-2x"></i>Erstellen neuen Auftrag </a>
    </div>

    <br />
    <div class="row">
        <div class="col-md-4">
            <div class="container-fluid">

                <div class="card card-info collapsed-card">
                    <div class="card-header">
                        <h3 class="card-title">Auftragssuche nach Datum </h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-plus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="card-body">
                            <!-- Date dd/mm/yyyy -->

                            <div class="form-group">
                                <label>Anfangsdatum:</label>
                                <div class="input-group date" id="reservationdate" data-target-input="nearest">
                                    <input type="text" class="form-control datetimepicker-input" data-target="#reservationdate">
                                    <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                <label>Enddatum:</label>

                                <div class="input-group date" id="reservationdate" data-target-input="nearest">
                                    <input type="text" class="form-control datetimepicker-input" data-target="#reservationdate">
                                    <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                    <div class="card-footer" style="display: none;">
                        <button type="button" class="btn btn-outline-info btn-block btn-flat"><i class="fa fa-search"></i> Suche</button>
                    </div>
                </div>

            </div>
        </div>

    </div>


    <div class="card-body">

        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Aufragnummer</th>
                    <th>Mandant</th>
                    <th>Einrichtung</th>
                    <th>Mitarbeiter</th>
                    <th>Datum</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                <tr class="odd">
                    <td>AUF000001</td>
                    <td>Awo</td>
                    <td>Lübbenau</td>
                    <td>Vüsal</td>
                    <td>01.01.2020</td>
                    <td>
                        <button type="button" class="btn btn-warning">Details</button> <button type="button" class="btn btn-info">Bearbeitung</button> <button type="button" class="btn btn-danger">Löschen</button>
                    </td>

                </tr>
                <tr class="odd">
                    <td>AUF000002</td>
                    <td>Procon</td>
                    <td>Lübbenau</td>
                    <td>Andre</td>
                    <td>01.01.2020</td>
                    <td>
                        <button type="button" class="btn btn-warning">Details</button> <button type="button" class="btn btn-info">Bearbeitung</button> <button type="button" class="btn btn-danger">Löschen</button>
                    </td>

                </tr>
                <tr class="odd">
                    <td>AUF000003</td>
                    <td>Integrations-und Service gGmbh</td>
                    <td>Guben</td>
                    <td>Mr.Xmen</td>
                    <td>01.01.2020</td>
                    <td>
                        <button type="button" class="btn btn-warning">Details</button> <button type="button" class="btn btn-info">Bearbeitung</button> <button type="button" class="btn btn-danger">Löschen</button>
                    </td>

                </tr>

            </tbody>
        </table>
    </div>


</div>

OrderOverview/OrderOverview.WebApp/Views/Home/Index.cshtml
    <!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Homepage</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Starter Page</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Card title 5</h5>

                        <p class="card-text">
                            Some quick example text to build on the card title and make up the bulk of the card's
                            content.
                        </p>

                        <a href="#" class="card-link">Card link</a>
                        <a href="#" class="card-link">Another link</a>
                    </div>
                </div>

                <div class="card card-primary card-outline">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>

                        <p class="card-text">
                            Some quick example text to build on the card title and make up the bulk of the card's
                            content.
                        </p>
                        <a href="#" class="card-link">Card link</a>
                        <a href="#" class="card-link">Another link</a>
                    </div>
                </div><!-- /.card -->
            </div>
            <!-- /.col-md-6 -->
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="m-0">Featured</h5>
                    </div>
                    <div class="card-body">
                        <h6 class="card-title">Special title treatment</h6>

                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>

                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h5 class="m-0">Featured</h5>
                    </div>
                    <div class="card-body">
                        <h6 class="card-title">Special title treatment</h6>

                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
            <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content -->

OrderOverview/OrderOverview.WebApp/Views/ProductCategory/Index.cshtml
@model  OrderOverview.Entities.ProductCategory
<br />

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-list"></i>
                        Produktkategorie
                    </h3>
                </div>
                <form role="form">
                    <div class="card-body">




                        <div class="col-md-2">
                            <button type="button" class="btn btn-outline-primary btn-block" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-plus-circle"></i> Neu</button>




                        </div>
                        <br />
                        <div class="callout callout-info">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th style="width: 10px">ID</th>
                                        <th>Name</th>
                                        <th>Erstellungsdatum</th>
                                        <th>Geändert am</th>
                                        <th>Geänderter Benutzername</th>
                                        <th>Status</th>
                                        <th style="width: 230px"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in ViewBag.Categories)
                                    {
                                        <tr>
                                            <td>@item.ID</td>
                                            <td>@item.Name</td>
                                            <td>
                                                @Convert.ToDateTime(item.CreatedOn).ToString("dd/MM/yyyy")
                                            </td>
                                            <td> @Convert.ToDateTime(item.ModifiedOn).ToString("dd/MM/yyyy")</td>
                                            <td>@item.ModifiedUserName</td>
                                            <td><span class="badge bg-success">@item.Status</span></td>
                                            <td>
                                                <button type="button" class="btn btn-info">Bearbeitung</button> <button type="button" class="btn btn-danger">Löschen</button>
                                            </td>
                                        </tr>
                                    }



                                </tbody>
                            </table>
                        </div>

                    </div>
                </form>
                <!-- /.card-header -->
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>



    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Fügen Sie eine neue Kategorie hinzu</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="new_category">
                        <label>Name</label>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Absagen</button>
                    <button type="button" class="btn btn-success" id="btnSubmit" data-redirect="@Url.Action("Index", "ProductCategory", new { ConfirmToastr = true})">Speichern</button>
                </div>
            </div>
        </div>
    </div>

</div>

@section aaa{


    @if (ViewBag.ConfirmSubmitMessage != null)  // bu paz islemir
    {
        <script type="text/javascript">
            myfunction();
        </script>
    }

    <script>

        function myfunction() {
            $(document).ready(function () {
                var Toast = Swal.mixin({
                    toast: true,
                    position: 'top-end',
                    showConfirmButton: false,
                    timer: 3000
                });
                Toast.fire({
                    icon: 'success',
                    title: 'Neue Kategorie wurde gespeichert..'

                })
            });
        }




        $(document).ready(function () {
            $("#btnSubmit").click(function () {

                var categoryFormData = $("#new_category").serialize();
                $.ajax({
                    type: "POST",
                    url: "/ProductCategory/Create",
                    data: categoryFormData,
                    success: function () {
                        window.location.href = $("#btnSubmit").data("redirect");
                    },
                    error: function () {
                        alert('Oppps!');
                    }

                })
            })
        })


    </script>


}